// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQvbACAcsxlhqAXAQtq5XNgGKH_RzzLjY',
    appId: '1:1089916246009:web:791c8e85bc520d77ab4f28',
    messagingSenderId: '1089916246009',
    projectId: 'chatapp-41199',
    authDomain: 'chatapp-41199.firebaseapp.com',
    storageBucket: 'chatapp-41199.appspot.com',
    measurementId: 'G-7BFLSB7VMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6I20z1WxNt0xKuZIsTVHktQssN8Pc9n8',
    appId: '1:1089916246009:android:7721524f30fac0e9ab4f28',
    messagingSenderId: '1089916246009',
    projectId: 'chatapp-41199',
    storageBucket: 'chatapp-41199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbpocKrlJngOwHKHzYMqRW5LPRIUcNlog',
    appId: '1:1089916246009:ios:842ecf7da4c3069bab4f28',
    messagingSenderId: '1089916246009',
    projectId: 'chatapp-41199',
    storageBucket: 'chatapp-41199.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );
}
